version: "3.9"
services:

  postgres:
    image: postgres:13.3
    container_name: "postgres"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"

  telegram_bot:
    build: bot.telegram
    container_name: "telegram_bot"
    ports:
      - "9090:9090"
    depends_on:
      - rabbitmq
    environment:
      - TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${BOT_NAME}
      - RABBIT_HOST=${RABBIT_HOST_ENV}

  mvc:
    build: ssu.web
    container_name: "app_mvc"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - RABBIT_HOST=${RABBIT_HOST_ENV}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"