server:
  port: 8080
spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  mvc:
    view:
      suffix: .html